# --> check the technical writing for various characteristics
- writing/report.md:
    - description: Ensure that report.md file exists in the writing/ directory
      check: ConfirmFileExists
    - description: Write a minimum number of meaningful words (250) in the report
      check: CountFileWords
      options:
        count: 250
        exact: false
    - description: Confirm that the markdown file has the correct number of headers
      check: CountMarkdownTags
      options:
        tag: heading
        count: 7
        exact: true
    - description: Complete all TODOs, remove the TODO markers in the report.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Replace the 'Add Your Names Here' prompt in the report file
      check: MatchFileFragment
      options:
        fragment: "Add Your Names Here"
        count: 0
        exact: true
    - description: Confirm that the markdown file has the correct number of fenced code blocks
      check: CountMarkdownTags
      options:
        tag: code_block
        count: 1
        exact: false
# count number of commits in the GitHub repository
- description: Have at least a specific minimum number of commits (25) in repository
  check: CountCommits
  options:
    count: 25
